import "../Styles/globals.css";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/config/muiTheme";
import { Navbar } from "@/components/Navbar/Navbar";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <ThemeProvider theme={theme}>
        <body suppressHydrationWarning={true} className={vazirmatn.className}>
          <Navbar />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
